# The URL the site will be built for
base_url = "/"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Syntax highlighting for code
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "css/syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "css/syntax-theme-light.css" },
]

# Make headings clickable (see `templates/anchor-link.html`)
insert_anchor_links = "heading"

# GitHub style alerts: e.g. IMPORTANT, NOTE, WARNING, etc...
github_alerts = true

# Enable footnotes with back-links at the bottom of the page
bottom_footnotes = true

[extra]
# Put all your custom variables here
