# This builds and publishes the site

# Run only on manual trigger
on:
  workflow_dispatch:

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # If publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
